---
version: "2.2"

services:
  sim_node:
    scale: 1
    image: gazebo_ros_vsm_demo
    ports:
      - 8080
    environment:
      - SPAWN_X=0
      - SPAWN_Y=0
      - SPAWN_YAW=0
      - VSM_NAME=test_name
      - VSM_ADDRESS=localhost
      - VSM_PORT=11511
      - VSM_VERBOSITY=2
    build:
      dockerfile: docker/Dockerfile
      context: ..
