---
version: "2.3"

services:
  sim_node:
    scale: 2
    image: gazebo_vsm_demo
    ports:
      - 8080
    environment:
      - VSM_RANGE=10
      - VSM_EXPIRY=10000
      - VSM_VERBOSITY=2
    build:
      dockerfile: docker/Dockerfile
      context: ..
