---
# Virtual Space Meshnet Config

# Display name of this node.
name: $VSM_NAME

# Publicly reachable network hostname or address.
address: $VSM_HOST

# (address:port)
# Edpoint of known peers within the mesh to join.
bootstrap_peers:
  - $VSM_BOOTSTRAP_PEER 

# UDP port of the mesh network.
port: $VSM_PORT

# Select UDP vs TCP (tcp is buggy ATM)
protocol: udp

# (meters 2D)
# Default center of simulation.
initial_coordinates: [0, 0]

# Peer connections are maintained only when there are common bits in their group mask.
group_mask: 0xFFFFFFFF

# (miliseconds)
# How often to broadcast peer update beacon.
peer_update_interval: 500

# Number of peer update intervals to retain record of known peers.
tracking_duration: 20

# (miliseconds)
# How often to poll for expired entities.
entity_expiry_interval: 500

# Max number of stale entity timestamps to store.
# Lookup is queried to reject already received updates.
timestamp_lookup_size: 1024

# (bytes)
# Size of entities payload, message size aprox 600B more but may vary.
# Use to limit message size below network MTU to avoid UDP fragmentation.
entity_updates_size: 0

# Verbosity levels
# 0 - Trace
# 1 - Debug
# 2 - Info
# 3 - Warn
# 4 - Error
# 5 - Fatal
verbosity: $VSM_VERBOSITY

# Name of entity to center simulation around.
tracked_entity: $VSM_NAME

# Remap entity names on spawn.
# Convenient for creating unique instances of synced entities.
remapped_entities:
  "/" : $VSM_NAME

# List of entity name patterns to synchronize.
# Synced entity is associated with the first name pattern matched.
# Regex format: https://en.cppreference.com/w/cpp/regex/ecmascript
# filter 0 -> (receive and forward updates only), 1 -> (broadcast using nearest routing filter)
# range and hop limit 0 -> inf
synced_entities:
  - name_pattern: $VSM_NAME
    filter: 1
    hop_limit: 0
    range: $VSM_RANGE
    expiry: $VSM_EXPIRY

  - name_pattern: "robot.*"
    filter: 0
    hop_limit: 0
    range: $VSM_RANGE
    expiry: $VSM_EXPIRY

  - name_pattern: "Construction.*"
    filter: 1
    hop_limit: 0
    range: 20
    expiry: $VSM_EXPIRY

  - name_pattern: "Dumpster.*"
    filter: 1
    hop_limit: 0
    range: 20
    expiry: $VSM_EXPIRY

  - name_pattern: "box.*"
    filter: 1
    hop_limit: 0
    range: 10
    expiry: $VSM_EXPIRY
